/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package j4rent.Locatarios;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;
import Funcoes.CEPEndereco;
import Funcoes.ClienteViaCepWS;
import Funcoes.TableControl;
import Funcoes.newTable;
import com.jgoodies.forms.factories.*;
import com.jgoodies.forms.layout.*;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author supervisor
 */
public class BuscaCep extends javax.swing.JDialog {
    int tam = 0, n = 0;
    public Object[] dados = null;
    
    /**
     * Creates new form BuscaCep
     */
    public BuscaCep(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        List<String> list = new ArrayList<>();
        list.add("AC"); list.add("AL"); list.add("AP");
        list.add("AM"); list.add("BA"); list.add("CE");
        list.add("DF"); list.add("ES"); list.add("GO");
        list.add("MA"); list.add("MT"); list.add("MS");
        list.add("MG"); list.add("PA"); list.add("PB");
        list.add("PR"); list.add("PE"); list.add("PI");
        list.add("RJ"); list.add("RN"); list.add("RS");
        list.add("RO"); list.add("RR"); list.add("SC");
        list.add("SP"); list.add("SE"); list.add("TO");
        for (String item : list) jComboBoxUf.addItem(item);
        jComboBoxUf.setSelectedItem("RJ");
        
        List<String> listaCid = new ArrayList<>();
        listaCid.add("Niteroi"); listaCid.add("Sao Goncalo");
        listaCid.add("Itaborai"); listaCid.add("Rio de Janeiro");
        for (String item : listaCid) jComboBoxCidade.addItem(item);
        
        String[] aheaders = {"Siafi","Endereço","Complto","Bairro","Cidade","Uf","Cep"};
        int[] widths = {0,500,300,200,200,100,150};
        String[] aligns = {"L","L","L","L","L","L","L"};
        newTable.InitTable(tblCEPS, aheaders, widths, aligns, true);
        
        setLocationRelativeTo(null);
    }

    private void SeekCep(String ctexto) {
        TableControl.Clear(tblCEPS);
        
        ClienteViaCepWS client = new ClienteViaCepWS();
                
        List<CEPEndereco> enderecos = null;
        enderecos = client.buscaEnderecos(jComboBoxUf.getSelectedItem().toString(), jComboBoxCidade.getSelectedItem().toString(), ctexto);
        
        if (enderecos.size() != 0) {
            tam = enderecos.size();
            n = 1;
            jbarra.setValue(0);
            jbarra.setVisible(true);
            for (CEPEndereco item : enderecos) {
                    new Thread() {
                        public void run() {
                            int pos = (n * 100) / tam;
                            try {sleep(100);} catch (Exception ex) {}
                            jbarra.setValue(pos);
                            jbarra.repaint();
                        }
                    }.start();                

                    Object[] linha = {item.getSiaf(),item.getLogradouro(),item.getComplemento(), item.getBairro(), item.getLocalidade(), item.getUf(), item.getCep()};
                    newTable.add(tblCEPS, linha);

                    n++;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Endereço não encontrado!\n\nEntre com um Endereço válido.","Cep", WARNING_MESSAGE);
        }
        
        jbarra.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        tblCEPS = new JTable();
        jbarra = new JProgressBar();
        jLabel1 = new JLabel();
        txtBuscar = new JTextField();
        jbtBuscar = new JButton();
        jLabel2 = new JLabel();
        jComboBoxUf = new JComboBox<>();
        jComboBoxCidade = new JComboBox<>();
        jLabel3 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:: Busca de Cep por endere\u00e7o...");
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);
        Container contentPane = getContentPane();

        //======== jScrollPane1 ========
        {

            //---- tblCEPS ----
            tblCEPS.setModel(new DefaultTableModel());
            tblCEPS.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tblCEPS.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    tblCEPSMouseClicked(e);
                }
            });
            jScrollPane1.setViewportView(tblCEPS);
        }

        //---- jLabel1 ----
        jLabel1.setText("Endere\u00e7o:");

        //---- jbtBuscar ----
        jbtBuscar.setIcon(new ImageIcon(getClass().getResource("/Figuras/find.png")));
        jbtBuscar.setMnemonic('B');
        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(e -> jbtBuscarActionPerformed(e));

        //---- jLabel2 ----
        jLabel2.setText("Estado:");

        //---- jComboBoxUf ----
        jComboBoxUf.setModel(new DefaultComboBoxModel<>(new String[] {

        }));

        //---- jComboBoxCidade ----
        jComboBoxCidade.setModel(new DefaultComboBoxModel<>(new String[] {

        }));

        //---- jLabel3 ----
        jLabel3.setText("Cidade:");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(5, 5, 5)
                            .addComponent(jComboBoxUf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jLabel3)
                            .addGap(5, 5, 5)
                            .addComponent(jComboBoxCidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jLabel1)
                            .addGap(5, 5, 5)
                            .addComponent(txtBuscar)
                            .addGap(18, 18, 18)
                            .addComponent(jbtBuscar))
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 848, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbarra, GroupLayout.PREFERRED_SIZE, 848, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(9, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxUf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxCidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtBuscar)
                        .addComponent(txtBuscar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(jbarra, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        new Thread() {public void run() {SeekCep(txtBuscar.getText());}}.start();
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void tblCEPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCEPSMouseClicked
        int row = tblCEPS.getSelectedRow(); 
        if (row < 0) {
            dados = null;
        } else {
            if (evt.getClickCount() == 2) {
                String slogra = tblCEPS.getModel().getValueAt(row, 0).toString();
                String sender = tblCEPS.getModel().getValueAt(row, 1).toString();
                String sbairr = tblCEPS.getModel().getValueAt(row, 3).toString();
                String scidad = tblCEPS.getModel().getValueAt(row, 4).toString();
                String sestad = tblCEPS.getModel().getValueAt(row, 5).toString();
                String scep   = tblCEPS.getModel().getValueAt(row, 6).toString();
                dados = new Object[] {slogra, sender, sbairr, scidad, sestad, scep};
                
                this.dispose();
            }
        }
    }//GEN-LAST:event_tblCEPSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscaCep dialog = new BuscaCep(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane jScrollPane1;
    private JTable tblCEPS;
    private JProgressBar jbarra;
    private JLabel jLabel1;
    private JTextField txtBuscar;
    private JButton jbtBuscar;
    private JLabel jLabel2;
    private JComboBox<String> jComboBoxUf;
    private JComboBox<String> jComboBoxCidade;
    private JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
