package j4rent.Locatarios.PreContrato;

import java.awt.event.KeyEvent;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Samic
 */
public class EditorMaker extends javax.swing.JInternalFrame {
    private EditorMakerModel tablemodel = new EditorMakerModel();
    private TableRowSorter<EditorMakerModel> sorter;
    
    /**
     * Creates new form EditorMaker
     */
    public EditorMaker() {
        initComponents();
        
        FillVariaveis();
        SwingUtilities.invokeLater(new Runnable(){ public void run(){ try{ jBusca.requestFocus(true); }catch(Exception e){} } });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaVariaveis = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        variaveis = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBusca = new javax.swing.JTextField();
        btnClear = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnMauiuscula = new javax.swing.JButton();
        btnMinuscula = new javax.swing.JButton();
        btnCapitular = new javax.swing.JButton();
        btnExtenso = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        formTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        formMask = new javax.swing.JComboBox<>();
        btnLancar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnIgual = new javax.swing.JButton();
        btnMaiorIgual = new javax.swing.JButton();
        btnMaior = new javax.swing.JButton();
        btnMenor = new javax.swing.JButton();
        btnMenorIgual = new javax.swing.JButton();
        btnDiferente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        copyTranf = new javax.swing.JLabel();
        btnClearTrans = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transferir = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Variaveis do Sistema para Editores de Texto");

        tabelaVariaveis.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaVariaveisStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabelaVariaveis.addTab("Proprietários", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabelaVariaveis.addTab("Imóveis", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabelaVariaveis.addTab("Locatários", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabelaVariaveis.addTab("Sócios", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabelaVariaveis.addTab("Fiadores", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabelaVariaveis.addTab("Carteira", jPanel6);

        variaveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        variaveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                variaveisMouseClicked(evt);
            }
        });
        variaveis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                variaveisKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(variaveis);

        jLabel1.setText("Buscar:");

        jBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBuscaKeyReleased(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/clear.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Funções"));

        btnLimpar.setText("Limpar");
        btnLimpar.setMaximumSize(new java.awt.Dimension(62, 25));
        btnLimpar.setMinimumSize(new java.awt.Dimension(62, 25));
        btnLimpar.setPreferredSize(new java.awt.Dimension(62, 25));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnMauiuscula.setText("Maiúscula");
        btnMauiuscula.setMaximumSize(new java.awt.Dimension(62, 25));
        btnMauiuscula.setMinimumSize(new java.awt.Dimension(62, 25));
        btnMauiuscula.setPreferredSize(new java.awt.Dimension(62, 25));
        btnMauiuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMauiusculaActionPerformed(evt);
            }
        });

        btnMinuscula.setText("Minúscula");
        btnMinuscula.setMaximumSize(new java.awt.Dimension(62, 25));
        btnMinuscula.setMinimumSize(new java.awt.Dimension(62, 25));
        btnMinuscula.setPreferredSize(new java.awt.Dimension(62, 25));
        btnMinuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusculaActionPerformed(evt);
            }
        });

        btnCapitular.setText("Capitular");
        btnCapitular.setMaximumSize(new java.awt.Dimension(62, 25));
        btnCapitular.setMinimumSize(new java.awt.Dimension(62, 25));
        btnCapitular.setPreferredSize(new java.awt.Dimension(62, 25));
        btnCapitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapitularActionPerformed(evt);
            }
        });

        btnExtenso.setText("Extenso");
        btnExtenso.setMaximumSize(new java.awt.Dimension(62, 25));
        btnExtenso.setMinimumSize(new java.awt.Dimension(62, 25));
        btnExtenso.setPreferredSize(new java.awt.Dimension(62, 25));
        btnExtenso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtensoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMauiuscula, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinuscula, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnCapitular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtenso, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMauiuscula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinuscula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExtenso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Formatação"));

        jLabel3.setText("Tipo:");

        formTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caracteres", "Data", "Valor" }));
        formTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formTipoActionPerformed(evt);
            }
        });

        jLabel4.setText("Mascara:");

        formMask.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "###.###.###-##", "###.###.###-##", "###.###.###-#" }));

        btnLancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/plus.png"))); // NOI18N
        btnLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formMask, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLancar)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(formMask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(formTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Condição"));

        btnIgual.setText("==");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnMaiorIgual.setText(">=");
        btnMaiorIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaiorIgualActionPerformed(evt);
            }
        });

        btnMaior.setText(">");
        btnMaior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaiorActionPerformed(evt);
            }
        });

        btnMenor.setText("<");
        btnMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorActionPerformed(evt);
            }
        });

        btnMenorIgual.setText("<=");
        btnMenorIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorIgualActionPerformed(evt);
            }
        });

        btnDiferente.setText("!=");
        btnDiferente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiferenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnIgual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaiorIgual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenorIgual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiferente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIgual)
                    .addComponent(btnMaiorIgual)
                    .addComponent(btnMaior)
                    .addComponent(btnMenor)
                    .addComponent(btnMenorIgual)
                    .addComponent(btnDiferente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Copiar:");

        copyTranf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/copy.png"))); // NOI18N
        copyTranf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                copyTranfMouseClicked(evt);
            }
        });

        btnClearTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/clear.png"))); // NOI18N
        btnClearTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearTransMouseClicked(evt);
            }
        });

        transferir.setColumns(20);
        transferir.setLineWrap(true);
        transferir.setRows(5);
        transferir.setWrapStyleWord(true);
        jScrollPane2.setViewportView(transferir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabelaVariaveis)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBusca)
                        .addGap(0, 0, 0)
                        .addComponent(btnClear))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyTranf)
                            .addComponent(btnClearTrans, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaVariaveis, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClearTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copyTranf))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaiorIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaiorIgualActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a condicionar","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".se(>= <expr>; <true>; <false>)"));
        int ipos = transferir.getText().indexOf("<expr>");
        transferir.select(ipos, ipos + 6);
        transferir.requestFocus();
    }//GEN-LAST:event_btnMaiorIgualActionPerformed

    private void btnMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaiorActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a condicionar","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".se(> <expr>; <true>; <false>)"));
        int ipos = transferir.getText().indexOf("<expr>");
        transferir.select(ipos, ipos + 6);
        transferir.requestFocus();
    }//GEN-LAST:event_btnMaiorActionPerformed

    private void btnMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a condicionar","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".se(< <expr>; <true>; <false>)"));
        int ipos = transferir.getText().indexOf("<expr>");
        transferir.select(ipos, ipos + 6);
        transferir.requestFocus();
    }//GEN-LAST:event_btnMenorActionPerformed

    private void btnMenorIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorIgualActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a condicionar","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".se(<= <expr>; <true>; <false>)"));
        int ipos = transferir.getText().indexOf("<expr>");
        transferir.select(ipos, ipos + 6);
        transferir.requestFocus();
    }//GEN-LAST:event_btnMenorIgualActionPerformed

    private void btnDiferenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiferenteActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a condicionar","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".se(!= <expr>; <true>; <false>)"));
        int ipos = transferir.getText().indexOf("<expr>");
        transferir.select(ipos, ipos + 6);
        transferir.requestFocus();
    }//GEN-LAST:event_btnDiferenteActionPerformed

    private void tabelaVariaveisStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaVariaveisStateChanged
        FillVariaveis();
    }//GEN-LAST:event_tabelaVariaveisStateChanged

    private void jBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscaKeyReleased
        if ("".equals(jBusca.getText().trim())) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter(jBusca.getText().trim()));
            } catch (PatternSyntaxException pse) {
                System.err.println("Bad regex pattern");
            }
        }
    }//GEN-LAST:event_jBuscaKeyReleased

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        jBusca.setText("");
        sorter.setRowFilter(null);
    }//GEN-LAST:event_btnClearMouseClicked

    private void formTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formTipoActionPerformed
        if (formTipo.getSelectedIndex() == -1) return;
        String[][] mask = {
            {"###.###.###-##", "###.###.###-##", "###.###.###-#"},
            {"dd-MM-yyyy", "dd 'de' MMMM 'de' yyyy", "hh:mm:ss"},
            {"Currency", "#0.00","#.##"}
        };
        
        formMask.removeAllItems();
        for (String item : mask[formTipo.getSelectedIndex()]) {
            formMask.addItem(item);
        }
    }//GEN-LAST:event_formTipoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a limpar","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".trim()"));
    }//GEN-LAST:event_btnLimparActionPerformed

    private void variaveisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_variaveisKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            FieldSelected();
        }
    }//GEN-LAST:event_variaveisKeyPressed

    private void variaveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_variaveisMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            FieldSelected();
        }        
    }//GEN-LAST:event_variaveisMouseClicked

    private void btnMauiusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMauiusculaActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a tornar maiuscula","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".toupper()"));
    }//GEN-LAST:event_btnMauiusculaActionPerformed

    private void btnMinusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusculaActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a tornar minuscula","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".tolower()"));
    }//GEN-LAST:event_btnMinusculaActionPerformed

    private void btnCapitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapitularActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a capitular","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".capitule()"));
    }//GEN-LAST:event_btnCapitularActionPerformed

    private void btnExtensoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtensoActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a extenso","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".extenso()"));
    }//GEN-LAST:event_btnExtensoActionPerformed

    private void btnLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a formatar","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, 
                tsel + ".format(" + formTipo.getSelectedItem().toString() + "," + 
                formMask.getSelectedItem().toString() + ")"));
    }//GEN-LAST:event_btnLancarActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        String tsel = transferir.getSelectedText();
        if (tsel == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar a expressão a condicionar","Atenção",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        transferir.setText(transferir.getText().replace(tsel, tsel + ".se(== <expr>; <true>; <false>)"));
        int ipos = transferir.getText().indexOf("<expr>");
        transferir.select(ipos, ipos + 6);
        transferir.requestFocus();
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnClearTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearTransMouseClicked
        transferir.setText("");
        transferir.requestFocus();
    }//GEN-LAST:event_btnClearTransMouseClicked

    private void copyTranfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyTranfMouseClicked
        transferir.selectAll();
        transferir.copy();
        transferir.setText("");
    }//GEN-LAST:event_copyTranfMouseClicked

    private void FieldSelected() {
        int car = transferir.getCaretPosition();
        String anttxt = transferir.getText().substring(0,car);
        String postxt = transferir.getText().substring(car);
        String newtxt = anttxt + "<@" + getDataBaseName(tabelaVariaveis.getSelectedIndex()) + "=" + variaveis.getValueAt(variaveis.getSelectedRow(),1) + "/>" + postxt;
        transferir.setText(newtxt);
    }

    private String getDataBaseName(int value) {
        String retorno = null;
        switch (value) {
            case 0:
                retorno = "prop";
                break;
            case 1:
                retorno = "imov";
                break;
            case 2:
                retorno = "loca";
                break;
            case 3:
                retorno = "soci";
                break;
            case 4:
                retorno = "fiad";
                break;
            case 5:
                retorno = "cart";
                break;
            default:
                retorno = null;
        }
        return retorno;        
    }
    
    private void FillVariaveis() {
        variaveis.setModel(tablemodel);
        
        int[] Size = {10,200,100};
        for (int i = 0; i < tablemodel.getColumnCount(); i++) {
            variaveis.getColumnModel().getColumn(i).setPreferredWidth(Size[i]);

            if (Size[i] == 0) {
                TableColumn tableColumn = variaveis.getColumn(variaveis.getColumnName(i));
                tableColumn.setPreferredWidth(0);
                tableColumn.setMinWidth(0);
                tableColumn.setMaxWidth(0);

                variaveis.getTableHeader().setReorderingAllowed(false);
                variaveis.getTableHeader().setResizingAllowed(false);
            }            
        }

        // Zera a tabela
        tablemodel.clear();
        Object[][] vars = DatabaseVariables(tabelaVariaveis.getSelectedIndex());
        for (Object[] item : vars) {
            EditorMakerClass _vars = new EditorMakerClass(item[0].toString(), item[1].toString(), item[2].toString());
            tablemodel.addRow(_vars);
        }
        variaveis.getColumnModel().getColumn(0).setPreferredWidth(0);
        TableColumn tableColumn = variaveis.getColumn(variaveis.getColumnName(0));
        tableColumn.setPreferredWidth(0);
        tableColumn.setMinWidth(0);
        tableColumn.setMaxWidth(0);

        variaveis.getTableHeader().setReorderingAllowed(false);
        variaveis.getTableHeader().setResizingAllowed(false);
                
        variaveis.getColumnModel().getColumn(1).setPreferredWidth(100);
        variaveis.getColumnModel().getColumn(2).setPreferredWidth(300);
        
        sorter = new TableRowSorter<EditorMakerModel>(tablemodel);
        variaveis.setRowSorter(sorter);

        sorter.setRowFilter(null);
        jBusca.setText("");
        jBusca.requestFocus();
    }

    private Object[][] DatabaseVariables(int value) {
        Object[][] _prop = {
            {"rgprp","codigo","Código"},
            {"tipoprop","tipo","Tipo 'Fisica' ou 'Jurídica'"},
            {"sexo","sexo","Sexo"},
            {"nome","nome","nome"},
            {"end","endereco", "Endereço"},
            {"nun","numero","Número"},
            {"compl","complemento","Complemento"},
            {"bairro","bairro","Bairro"},
            {"cidade","cidade","Cidade"},
            {"estado","estado","Estado"},
            {"cep","cep","Cep"},
            {"tel","telefone","Telefone"},
            {"dtnasc","nascimento","Data de nascimento"},
            {"cpfcnpj","cpf_cnpj","Cpf ou Cnpj"},
            {"rginsc","rg_insc","RG ou Inscrição"},
            {"ecivil","estado_civil","Estado civil"},
            {"naciona","nacionalidade","Nacionalidade"},
            {"profissao","profissao","Profissão"},
            {"representante","represenrante","Representantre"},
            {"repdtnasc","repnasc","Data nascimento representante"},
            {"conjugue","conjugue","Conjugue"},
            {"conjdtnasc","dtnascconj","Data nascimento conjugue"},
            {"email","email","E-Mail"}            
        };
        Object[][] _imov = {
            {"rgimv","registro","Registro"},
            {"tpimovel","tipo","Tipo do Imóvel"},
            {"end","endereco","Endereço"},
            {"num","numero","Número"},
            {"compl","complemento","Complemento"},
            {"bairro","bairro","Bairro"},
            {"cidade","cidade","Cidade"},
            {"estado","estado","Estado"},
            {"cep","cep","Cep"},
            {"situacao","situacao","Situação"}
        };
        Object[][] _loca = {
            {"contrato","contrato","Contrato"},
            {"tploca","tipo","Tipo 'Física' ou 'Jurídica'"},
            {"cpfcnpj","cpf_cnpj","CPF ou CNPJ"},
            {"rginsc","rg_insc","RG ou Inscrição"},
            {"sexo","sexo","Sexo quando Física"},
            {"nomerazao","nome_razao","Nome ou Razão social"},
            {"fantasia","fantasia","Nome fantasia quando jurídica"},
            {"end","endereco","Endereço"},
            {"num","numero","Número"},
            {"compl","complemento","Complemento"},
            {"bairro","bairro","Bairro"},
            {"cidade","cidade","Cidade"},
            {"estado","estado","Estado"},
            {"cep","cep","Cep"},
            {"ecivil","ecivil","Estado civil"},
            {"naciona","nacionalidade","Nacionalidade"},
            {"tel","telefone","Telefone"},
            {"mae","mae","Mãe"},
            {"pai","pai","Pai"},
            {"email","email","E-Mail"},
            {"empresa","empresa","Empresa"},
            {"cargo","profissao","Profissão"},
            {"salario","salario","Salário"},
            {"conjugue","conjugue","Conjugue"},
            {"cjdtnasc", "dtnascconj","Data nascimento conjugue"}
        };
        Object[][] _soci = {
            {"socionome1","nome_1","Nome sócio 1"},
            {"sociodtnasc1","nascimento_1","Data nascimento sócio 1"},
            {"socioecivil1","ecivil_1","Estado civil sócio 1"},
            {"sociocpf1","cpf_1","Cpf do sócio 1"},
            {"sociorg1","rg_1","RG do sócio 1"},
            {"sociomae1","mae_1","Mãe do sócio 1"},
            {"sociopai1","pai_1","Pai do sócio 1"},
            {"sociocargo1","cargo_1","Cargo do sócio 1"},
            {"sociosalario1","salario_1","Salário do sócio 1"},

            {"socionome2","nome_2","Nome sócio 2"},
            {"sociodtnasc2","nascimento_2","Data nascimento sócio 2"},
            {"socioecivil2","ecivil_2","Estado civil sócio 2"},
            {"sociocpf2","cpf_2","Cpf do sócio 2"},
            {"sociorg2","rg_2","RG do sócio 2"},
            {"sociomae2","mae_2","Mãe do sócio 2"},
            {"sociopai2","pai_2","Pai do sócio 2"},
            {"sociocargo2","cargo_2","Cargo do sócio 2"},
            {"sociosalario2","salario_2","Salário do sócio 2"},
            
            {"socionome3","nome_3","Nome sócio 3"},
            {"sociodtnasc3","nascimento_3","Data nascimento sócio 3"},
            {"socioecivil3","ecivil_3","Estado civil sócio 3"},
            {"sociocpf3","cpf_3","Cpf do sócio 3"},
            {"sociorg3","rg_3","RG do sócio 3"},
            {"sociomae3","mae_3","Mãe do sócio 3"},
            {"sociopai3","pai_3","Pai do sócio 3"},
            {"sociocargo3","cargo_3","Cargo do sócio 3"},
            {"sociosalario3","salario_3","Salário do sócio 3"},
            
            {"socionome4","nome_4","Nome sócio 4"},
            {"sociodtnasc4","nascimento_4","Data nascimento sócio 4"},
            {"socioecivil4","ecivil_4","Estado civil sócio 4"},
            {"sociocpf4","cpf_4","Cpf do sócio 4"},
            {"sociorg4","rg_4","RG do sócio 4"},
            {"sociomae4","mae_4","Mãe do sócio 4"},
            {"sociopai4","pai_4","Pai do sócio 4"},
            {"sociocargo4","cargo_4","Cargo do sócio 4"},
            {"sociosalario4","salario_4","Salário do sócio 4"}            
        };
        Object[][] _fiad = {
            {"tploca","tipo_1","Tipo 'Física' ou 'Jurídica'"},
            {"cpfcnpj","cpf_cnpj_1","Cpf ou Cnpj"},
            {"rginsc","rg_insc_1","Rg ou Inscrição"},
            {"sexo","sexo_1","Sexo quando Física"},
            {"nomerazao","nome_razao_1","Nome ou Razão social"},
            {"fantasia","fantasia_1","Nome fantasia quando jurídica"},
            {"end","endereco_1","Endereço"},
            {"num","numero_1","Número"},
            {"compl","complemento_1","Complemento"},
            {"bairro","bairro_1","Bairro"},
            {"cidade","cidade_1","Cidade"},
            {"estado","estado_1","Estado"},
            {"cep","cep_1","Cep"},
            {"ecivil","ecivil_1","Estado civil"},
            {"naciona","nacionalidade_1","Nacionalidade"},
            {"tel","telefone_1","Telefone"},
            {"mae","mae_1","Mãe"},
            {"pai","pai_1","Pai"},
            {"email","email_1","E-Mail"},
            {"empresa","empresa_1","Empresa"},
            {"cargo","profissao_1","Profissão"},
            {"salario","salario_1","Salário"},
            {"conjugue","conjugue_1","Conjugue"},
            {"cjdtnasc", "dtnascconj_1","Data nascimento conjugue"},

            {"tploca","tipo_2","Tipo 'Física' ou 'Jurídica'"},
            {"cpfcnpj","cpf_cnpj_2","Cpf ou Cnpj"},
            {"rginsc","rg_insc_2","Rg ou Inscrição"},
            {"sexo","sexo_2","Sexo quando Física"},
            {"nomerazao","nome_razao_2","Nome ou Razão social"},
            {"fantasia","fantasia_2","Nome fantasia quando jurídica"},
            {"end","endereco_2","Endereço"},
            {"num","numero_2","Número"},
            {"compl","complemento_2","Complemento"},
            {"bairro","bairro_2","Bairro"},
            {"cidade","cidade_2","Cidade"},
            {"estado","estado_2","Estado"},
            {"cep","cep_2","Cep"},
            {"ecivil","ecivil_2","Estado civil"},
            {"naciona","nacionalidade_2","Nacionalidade"},
            {"tel","telefone_2","Telefone"},
            {"mae","mae_2","Mãe"},
            {"pai","pai_2","Pai"},
            {"email","email_2","E-Mail"},
            {"empresa","empresa_2","Empresa"},
            {"cargo","profissao_2","Profissão"},
            {"salario","salario_2","Salário"},
            {"conjugue","conjugue_2","Conjugue"},
            {"cjdtnasc", "dtnascconj_2","Data nascimento conjugue"},

            {"tploca","tipo_2","Tipo 'Física' ou 'Jurídica'"},
            {"cpfcnpj","cpf_cnpj_2","Cpf ou Cnpj"},
            {"rginsc","rg_insc_2","Rg ou Inscrição"},
            {"sexo","sexo_2","Sexo quando Física"},
            {"nomerazao","nome_razao_2","Nome ou Razão social"},
            {"fantasia","fantasia_2","Nome fantasia quando jurídica"},
            {"end","endereco_2","Endereço"},
            {"num","numero_2","Número"},
            {"compl","complemento_2","Complemento"},
            {"bairro","bairro_2","Bairro"},
            {"cidade","cidade_2","Cidade"},
            {"estado","estado_2","Estado"},
            {"cep","cep_2","Cep"},
            {"ecivil","ecivil_2","Estado civil"},
            {"naciona","nacionalidade_2","Nacionalidade"},
            {"tel","telefone_2","Telefone"},
            {"mae","mae_2","Mãe"},
            {"pai","pai_2","Pai"},
            {"email","email_2","E-Mail"},
            {"empresa","empresa_2","Empresa"},
            {"cargo","profissao_2","Profissão"},
            {"salario","salario_2","Salário"},
            {"conjugue","conjugue_2","Conjugue"},
            {"cjdtnasc", "dtnascconj_2","Data nascimento conjugue"}

        };
        Object[][] _cart = {
            {"DTINICIO","dtinicio","Data de inicio de Contrato"},
            {"DTTERMINO","dttermino","Data de fim de Contrato"},
            {"DTADITO","dtadito","Data de aditamento de Contrato"},
            {"DTVENCIMENTO","vencimento","Data de vencimento"},
            {"01","aluguel","Valor do Aluguel"},
            {"02","condominio","Valor do Condomínio"},
            {"07","iptu","Valor do IPTU"}            
        };
        Object[][] retorno = null;
        switch (value) {
            case 0:
                retorno = _prop;
                break;
            case 1:
                retorno = _imov;
                break;
            case 2:
                retorno = _loca;
                break;
            case 3:
                retorno = _soci;
                break;
            case 4:
                retorno = _fiad;
                break;
            case 5:
                retorno = _cart;
                break;
            default:
                retorno = null;
        }
        return retorno;
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapitular;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnClearTrans;
    private javax.swing.JButton btnDiferente;
    private javax.swing.JButton btnExtenso;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLancar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMaior;
    private javax.swing.JButton btnMaiorIgual;
    private javax.swing.JButton btnMauiuscula;
    private javax.swing.JButton btnMenor;
    private javax.swing.JButton btnMenorIgual;
    private javax.swing.JButton btnMinuscula;
    private javax.swing.JLabel copyTranf;
    private javax.swing.JComboBox<String> formMask;
    private javax.swing.JComboBox<String> formTipo;
    private javax.swing.JTextField jBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabelaVariaveis;
    private javax.swing.JTextArea transferir;
    private javax.swing.JTable variaveis;
    // End of variables declaration//GEN-END:variables
}
