/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Relatorios;

import Funcoes.Dates;
import Funcoes.DbMain;
import Funcoes.VariaveisGlobais;
import Funcoes.jDirectory;
import Funcoes.toPreview;
import j4rent.Partida.Collections;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import javax.swing.JComboBox;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.export.JRPdfExporter;

/**
 *
 * @author supervisor
 */
public class jDespesas extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.conexao;

    /**
     * Creates new form jDespesas
     */
    public jDespesas() {
        initComponents();
        
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);

        jDtInicial.setText(Dates.DateFormata("dd/MM/yyyy", new Date()));
        jDtFinal.setText(Dates.DateFormata("dd/MM/yyyy", new Date()));
        FillGrupos(jGrupo);
        
    }

    private void FillGrupos(JComboBox table) {
        String tsql = "SELECT buffer, autoid FROM jgeral.combobuffer WHERE local = 'DESPES' ORDER BY Upper(buffer);";
        ResultSet tbgrupo = conn.AbrirTabela(tsql, ResultSet.CONCUR_READ_ONLY);
        try {
            jGrupo.removeAllItems();
            jGrupo.addItem("0 - Todos os Grupos");
            while (tbgrupo.next()) {
                String tautoid = tbgrupo.getString("autoid");
                String tdescric = tbgrupo.getString("buffer");

                jGrupo.addItem(tautoid + " - " + tdescric);
            }
        } catch (Exception err) {}
        DbMain.FecharTabela(tbgrupo);
    }
    
    private void Despesas(String dtInic, String dtFinal, String gGrupo) {
        Collections gVar = VariaveisGlobais.dCliente;
        
        Map parametros = new HashMap();
        dtInic = dtInic.substring(6,10) + "-" + dtInic.substring(3,5) + "-" + dtInic.substring(0,2);
        dtFinal = dtFinal.substring(6,10) + "-" + dtFinal.substring(3,5) + "-" + dtFinal.substring(0,2);
        parametros.put("parameter1", dtInic);
        parametros.put("parameter2", dtFinal);
        parametros.put("parameter3", Integer.parseInt(gGrupo.substring(0,gGrupo.indexOf("-") - 1)));
        
        try {
            String fileName = "reports/rDespesas3.jasper";
            JasperPrint print = JasperFillManager.fillReport(fileName, parametros, conn.conn);

            // Create a PDF exporter
            JRExporter exporter = new JRPdfExporter();

            new jDirectory("reports/Relatorios/" + Dates.iYear(new Date()) + "/" + Dates.Month(new Date()) + "/");
            String pathName = "reports/Relatorios/" + Dates.iYear(new Date()) + "/" + Dates.Month(new Date()) + "/";
            
            // Configure the exporter (set output file name and print object)
            String outFileName = pathName + "despesas_" + Dates.DateFormata("ddMMyyyy", new Date()) + "_" + dtInic.replace("/", "_") + "_" + dtFinal.replace("/", "_") + ".pdf";
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, outFileName);
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);

            // Export the PDF file
            exporter.exportReport();
            
            new toPreview(outFileName);
                
        } catch (JRException e) {
            e.printStackTrace();
            System.exit(1);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDtInicial = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jDtFinal = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jGrupo = new javax.swing.JComboBox<>();
        jbtnPreview = new javax.swing.JButton();

        setClosable(true);
        setTitle(".:: Relatório de Despesas");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Data:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, -1, -1));

        try {
            jDtInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jDtInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 6, 92, -1));

        jLabel2.setText("até");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 12, -1, -1));

        try {
            jDtFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jDtFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 6, 92, -1));

        jLabel3.setText("Grupo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, -1, -1));

        jGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 39, 209, -1));

        jbtnPreview.setText("Preview");
        jbtnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreviewActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 6, -1, 58));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreviewActionPerformed
        jbtnPreview.setEnabled(false);
        Despesas(jDtInicial.getText(), jDtFinal.getText(), jGrupo.getSelectedItem().toString());
        jbtnPreview.setEnabled(true);
    }//GEN-LAST:event_jbtnPreviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jDtFinal;
    private javax.swing.JFormattedTextField jDtInicial;
    private javax.swing.JComboBox<String> jGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnPreview;
    // End of variables declaration//GEN-END:variables
}
