/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Relatorios;

import Funcoes.Dates;
import Funcoes.DbMain;
import Funcoes.LerValor;
import Funcoes.VariaveisGlobais;
import Funcoes.jDirectory;
import Funcoes.toPreview;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Samic
 */
public class rMultas extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.conexao;
    
    /**
     * Creates new form rMultas
     */
    public rMultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle(".:: Relatorio de Multas Lançadas REGRAS");
        setVisible(true);

        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<classMulta> listas = new ArrayList<>();
        classMulta bean1 = new classMulta();
        
        try {
            String admmulta = LerValor.FormatNumber(conn.LerParametros("PA_MULTA"), 3);
            String admcorrecao = LerValor.FormatNumber(conn.LerParametros("PA_CORR"), 3);
            String admjuros = LerValor.FormatNumber(conn.LerParametros("PA_JUROS"), 3);
            String admexpediente = LerValor.FormatNumber(conn.LerParametros("PA_TXEXP"), 3);

            String multares = LerValor.FormatNumber(conn.LerParametros("MULTA_RES"), 3);
            String multacom = LerValor.FormatNumber(conn.LerParametros("MULTA_COM"), 3);
            
            String cortipo = String.valueOf(Integer.parseInt(conn.LerParametros("COR_TIPO")));
            String corlim = String.valueOf(Integer.parseInt(conn.LerParametros("COR_LIM_SN")));
            String corlima = LerValor.FormatNumber(conn.LerParametros("COR_LIM_A"), 0);
            String corperc = LerValor.FormatNumber(conn.LerParametros("COR_CORR"), 3);
            String jurosperc = LerValor.FormatNumber(conn.LerParametros("JUR_PER"), 3);
            String diasmulta = LerValor.FormatNumber(conn.LerParametros("DIA_MUL"), 0);
            String diascorrecao = LerValor.FormatNumber(conn.LerParametros("DIA_COR"), 0);
            String diasjuros = LerValor.FormatNumber(conn.LerParametros("DIA_JUR"), 0);
            String expperc = LerValor.FormatNumber(conn.LerParametros("TE_PER"), 3);
            String expminimo = LerValor.FormatNumber(conn.LerParametros("TE_VRM"), 2);
            String expnome = (conn.LerParametros("TE_NOME") == null ? "Tx.Expediente" : conn.LerParametros("TE_NOME"));
            String comissao = LerValor.FormatNumber(conn.LerParametros("COMISSAO"), 3);
            String jurostipo = (conn.LerParametros("JUROS").equalsIgnoreCase("SIMPLES") ? "0" : "1");
            String dtgrava = null;
            try {
                dtgrava = conn.LerParametros("MULTADTGRAV");
            } catch (SQLException e) {}
            if (dtgrava == null) dtgrava = "";
                    
            bean1.setTIPO("G");
            bean1.setPA_MULTA(admmulta);
            bean1.setPA_COR(admcorrecao);
            bean1.setPA_JUR(admjuros);
            bean1.setTXEXP(admexpediente);
            bean1.setMULTA_RES(multares);
            bean1.setMULTA_COM(multacom);
            bean1.setCOR_TIPO(cortipo);            
            bean1.setCOR_LIM_A(corlima);            
            bean1.setCOR_CORR(corperc);            
            bean1.setDIA_MUL(diasmulta);
            bean1.setDIA_COR(diascorrecao);
            bean1.setDIA_JUR(diasjuros);
            bean1.setPER_JUR(jurosperc);            
            bean1.setTE_PER(expperc);
            bean1.setTE_VRM(expminimo);
            bean1.setTE_NOME(expnome);
            bean1.setCOMISSAO(comissao);
            bean1.setREGRA(jurostipo);
            bean1.setRGPRP("");
            bean1.setRGIMV("");
            bean1.setDATAGRAVACAO(dtgrava);
            bean1.setDESATIVADO("0");
            
            listas.add(bean1);
        } catch (SQLException e) {}
        
        // Multas Proprietarios
        String sSql = "SELECT PA_MULTA,PA_COR,PA_JUR,MULTA_RES,MULTA_COM," +
                      "COR_TIPO,COR_CORR,PER_JUR,DIA_MUL,DIA_COR," +
                      "DIA_JUR,TE_PER,TE_VRM,TE_NOME,TXEXP,TBRLIQ," +
                      "REGRA,RGPRP,RGIMV,COR_LIM_A,COMISSAO,DATAGRAVACAO " +
                      "FROM multa WHERE (RGPRP != NULL OR RGPRP != '') AND " + 
                      "(RGIMV IS NULL OR RGIMV = '') ORDER BY DATAGRAVACAO DESC, RGPRP;";
        if (!sSql.isEmpty()) {
            ResultSet hRs = this.conn.AbrirTabela(sSql, ResultSet.CONCUR_READ_ONLY);

            try {
                while (hRs.next()) {
                    String sativo = "1";
                    String[][] argprp = null;
                    try {
                        argprp = conn.LerCamposTabela(new String[] {"status"}, "proprietarios", "rgprp = '" + hRs.getString("RGPRP") + "'");
                    } catch (SQLException e) {}
                    if (argprp != null) {
                        if (argprp[0][3].toString().toUpperCase().equalsIgnoreCase("ATIVO")) sativo = "0"; else sativo = "1";
                        
                        bean1 = new classMulta();
                        bean1.setTIPO("P");
                        bean1.setPA_MULTA(LerValor.FormatNumber(hRs.getString("PA_MULTA"), 3));
                        bean1.setPA_COR(LerValor.FormatNumber(hRs.getString("PA_COR"), 3));
                        bean1.setPA_JUR(LerValor.FormatNumber(hRs.getString("PA_JUR"), 3));
                        bean1.setTXEXP(LerValor.FormatNumber(hRs.getString("TXEXP"), 3));
                        bean1.setMULTA_RES(LerValor.FormatNumber(hRs.getString("MULTA_RES"), 3));
                        bean1.setMULTA_COM(LerValor.FormatNumber(hRs.getString("MULTA_COM"), 3));
                        bean1.setCOR_TIPO(LerValor.FormatNumber(hRs.getString("COR_TIPO"), 0));            
                        bean1.setCOR_LIM_A(LerValor.FormatNumber(hRs.getString("COR_LIM_A"), 0));            
                        bean1.setCOR_CORR(LerValor.FormatNumber(hRs.getString("COR_CORR"), 3));            
                        bean1.setDIA_MUL(LerValor.FormatNumber(hRs.getString("DIA_MUL"), 0));
                        bean1.setDIA_COR(LerValor.FormatNumber(hRs.getString("DIA_COR"), 0));
                        bean1.setDIA_JUR(LerValor.FormatNumber(hRs.getString("DIA_JUR"), 0));
                        bean1.setPER_JUR(LerValor.FormatNumber(hRs.getString("PER_JUR"), 3));            
                        bean1.setTE_PER(LerValor.FormatNumber(hRs.getString("TE_PER"), 3));
                        bean1.setTE_VRM(LerValor.FormatNumber(hRs.getString("TE_VRM"), 2));
                        String tenome = hRs.getString("TE_NOME");
                        bean1.setTE_NOME(tenome == null ? "Tx. Expediente" : tenome);
                        bean1.setCOMISSAO(LerValor.FormatNumber(hRs.getString("COMISSAO"), 3));
                        bean1.setREGRA(hRs.getString("REGRA").toString().equalsIgnoreCase("0") ? "0" : "1");
                        bean1.setRGPRP(hRs.getString("RGPRP"));
                        bean1.setRGIMV("");

                        Date dtgr; String sdtgr = "";
                        try {
                            dtgr = hRs.getDate("DATAGRAVACAO");
                            if (dtgr != null) sdtgr = Dates.DateFormata("dd-MM-yyyy", dtgr);
                        } catch (SQLException e) {} 

                        bean1.setDATAGRAVACAO(sdtgr);

                        bean1.setDESATIVADO(sativo);
                        listas.add(bean1);                    
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            DbMain.FecharTabela(hRs);
        }
        
        // Multas Imoveis/Locatarios
        sSql = "SELECT PA_MULTA,PA_COR,PA_JUR,MULTA_RES,MULTA_COM," +
                      "COR_TIPO,COR_CORR,PER_JUR,DIA_MUL,DIA_COR," +
                      "DIA_JUR,TE_PER,TE_VRM,TE_NOME,TXEXP,TBRLIQ," +
                      "REGRA,RGPRP,RGIMV,COR_LIM_A,COMISSAO,DATAGRAVACAO " +
                      "FROM multa WHERE (RGPRP != NULL OR RGPRP != '') AND " + 
                      "(RGIMV IS NOT NULL OR RGIMV != '') ORDER BY DATAGRAVACAO DESC, RGIMV;";
        if (!sSql.isEmpty()) {
            ResultSet hRs = this.conn.AbrirTabela(sSql, ResultSet.CONCUR_READ_ONLY);

            try {
                while (hRs.next()) {
                    String sativo = "1";
                    String scontrato = "";
                    String[][] acontrato = null;
                    try {
                        acontrato = conn.LerCamposTabela(new String[] {"contrato", "fiador1uf"}, "locatarios", "rgimv = '" + hRs.getString("RGIMV") + "'");
                    } catch (SQLException e) {}
                    if (acontrato != null) {                        
                        scontrato = acontrato[0][3].toString();
                        String rativo = acontrato[1][3];
                        if (rativo == null) rativo = "";
                        if (rativo.equalsIgnoreCase("X")) sativo = "1"; else sativo = "0";
                        
                        bean1 = new classMulta();
                        bean1.setTIPO("L");
                        bean1.setPA_MULTA(LerValor.FormatNumber(hRs.getString("PA_MULTA"), 3));
                        bean1.setPA_COR(LerValor.FormatNumber(hRs.getString("PA_COR"), 3));
                        bean1.setPA_JUR(LerValor.FormatNumber(hRs.getString("PA_JUR"), 3));
                        bean1.setTXEXP(LerValor.FormatNumber(hRs.getString("TXEXP"), 3));
                        bean1.setMULTA_RES(LerValor.FormatNumber(hRs.getString("MULTA_RES"), 3));
                        bean1.setMULTA_COM(LerValor.FormatNumber(hRs.getString("MULTA_COM"), 3));
                        bean1.setCOR_TIPO(LerValor.FormatNumber(hRs.getString("COR_TIPO"), 0));            
                        bean1.setCOR_LIM_A(LerValor.FormatNumber(hRs.getString("COR_LIM_A"), 0));            
                        bean1.setCOR_CORR(LerValor.FormatNumber(hRs.getString("COR_CORR"), 3));            
                        bean1.setDIA_MUL(LerValor.FormatNumber(hRs.getString("DIA_MUL"), 0));
                        bean1.setDIA_COR(LerValor.FormatNumber(hRs.getString("DIA_COR"), 0));
                        bean1.setDIA_JUR(LerValor.FormatNumber(hRs.getString("DIA_JUR"), 0));
                        bean1.setPER_JUR(LerValor.FormatNumber(hRs.getString("PER_JUR"), 3));            
                        bean1.setTE_PER(LerValor.FormatNumber(hRs.getString("TE_PER"), 3));
                        bean1.setTE_VRM(LerValor.FormatNumber(hRs.getString("TE_VRM"), 2));
                        String tenome = hRs.getString("TE_NOME");
                        bean1.setTE_NOME(tenome == null ? "Tx. Expediente" : tenome);
                        bean1.setCOMISSAO(LerValor.FormatNumber(hRs.getString("COMISSAO"), 3));
                        bean1.setREGRA(hRs.getString("REGRA").toString().equalsIgnoreCase("0") ? "0" : "1");
                        bean1.setRGPRP("");
                        bean1.setRGIMV(scontrato);

                        Date dtgr; String sdtgr = "";
                        try {
                            dtgr = hRs.getDate("DATAGRAVACAO");
                            if (dtgr != null) sdtgr = Dates.DateFormata("dd-MM-yyyy", dtgr);
                        } catch (SQLException e) {} 

                        bean1.setDATAGRAVACAO(sdtgr);
                        bean1.setDESATIVADO(sativo);
                        
                        listas.add(bean1);                    
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            DbMain.FecharTabela(hRs);
        }
        
        JasperPrint jasperPrint = null;
        try {
            JRDataSource jrds = new JRBeanCollectionDataSource(listas);

            String reportFileName = "reports/Multas.jasper";
            JasperReport reporte = (JasperReport) JRLoader.loadObjectFromFile(reportFileName);
            jasperPrint = JasperFillManager.fillReport(reporte, null, jrds);

            JRPdfExporter exporter = new JRPdfExporter();

            try {
                new jDirectory("reports/Relatorios/" + Dates.iYear(new Date()) + "/" + Dates.Month(new Date()) + "/");
                String pathName = "reports/Relatorios/" + Dates.iYear(new Date()) + "/" + Dates.Month(new Date()) + "/";

                // Configure the exporter (set output file name and print object)
                String FileNamePdf = pathName + "Multa_" + Dates.DateFormata("dd-MM-yyyy_HH_mm", new Date()) + ".pdf";
                String outFileName = FileNamePdf;
                
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, outFileName);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);

                exporter.exportReport();
                new toPreview(outFileName);
            } catch (Exception jex) {jex.printStackTrace();}
        } catch (JRException e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
